backend:
  name: git-gateway

media_folder: "site/themes/webective/static/img" # Folder where user uploaded files should go
public_folder: "img"

collections: # A list of collections the CMS should be able to edit
  - name: "pages"
    label: "Pages"
    files:
      - file: "site/content/about.md"
        label: "About Page"
        name: "about"
        fields:
          - {label: "Top Section", name: top_section, widget: text}
          - {label: "Who We are", name: who_we_are, widget: text}
          - {label: "Development Menu", name: development_menu, widget: list, fields: [
                {label: "Title", name: "title", widget: "string"}
              ]
            }
          - {label: "Web Design", name: ui_ux_menu, widget: list, fields: [
                {label: "Title", name: "title", widget: "string"}
              ]
            }
          - {label: "email", name: email, widget: string}
          - {label: "telephone", name: telephone, widget: string}
          - {label: "address", name: address, widget: string}
          - {label: "Client Logos", name: clients_logos, widget: list, fields: [
                {label: Image, name: image, widget: image}
              ]
            }
          # 
